### ISSUE TITLE
Migrate to dedicated Chinese conversion library

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openmaptiles-zh-modifier#1]
ICU is a decent starting point for Chinese conversion (or at least, more decent than for other scripts), especially since it’s accessible from so many languages. But ICU isn’t primarily designed for transliteration to display to the user; its constraints like reversibility make it better suited to use cases like collation and speech synthesis. Ideally, you’d use a dedicated Chinese conversion library that can handle more nuances between Chinese variants.

[OpenCC](https://github.com/BYVoid/OpenCC/) is a popular Chinese conversion library that, as far as I know, has a good reputation. It has official frontends in multiple languages, though none in Java. There are several unofficial Java ports, but none seem to be quite as popular or well maintained as the original OpenCC:

* [android-opencc](https://github.com/qichuan/android-opencc/)
* [jopencc](https://github.com/carlostse/jopencc/)
* [OpenCC-Java](https://github.com/yichen0831/OpenCC-Java)
* [opencc4j](https://github.com/houbb/opencc4j/)

**Comment by ZeLonewolf** [comment]
Resolved by adding in opencc4j which seems to work.
